### ISSUE TITLE
The search functionality for saved Shots is not working

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1369]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608180837

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on version (v 0.1.201608180837) is installed on a new profile.

[Steps to reproduce]:
1  Navigate to any web page.
2. Click on the "PageShot" button from browser toolbar.
3. Click the "My Shots" button.
4. In the search filed enter a word in order to perform a search for a saved shot.
5. Press the "Search" button.

[Expected result]:
- A search is successfully performed for the entered word. 

[Actual result]:
- Nothing happens. The search is not returning any results even if trying to search for an existing file

[Notes]:
- Added a screen recording with the issue: https://goo.gl/9Psq2y

**Comment by fzzzy** [comment]
11:08:00.144 ReferenceError: sendEvent is not defined
shotindex-bundle.js:227:9 onSubmitForm

**Comment by ianb** [comment]
I would have expected 2b63e8584702af3dee3c795d44e3de0a3e71acd8 to fix the sendEvent bug

**Comment by fzzzy** [comment]
@ianb you are correct. My repo was out of date. This is already fixed in master.

**Comment by SoftVision-CosminMuntean** [comment]
I have created a custom pageshot build (v0.1.201608220738) from github repository and I can still reproduce the issue. The search is not returning any results even if trying to search for an existing file.
This error appeared in the browser console after I pressed the "Search" button:

![search](https://cloud.githubusercontent.com/assets/19226534/17862294/52491476-689d-11e6-8f1e-8d0a6d22d2e0.png)

**Comment by fzzzy** [comment]
That's odd. It works here with HEAD, and when I do `curl -v http://localhost:10080/shots` the `Content-Security-Policy` header has 'self' as a valid script-src:

`Content-Security-Policy: default-src 'self'; img-src 'self' www.google-analytics.com localhost:10081 data:; script-src 'self' www.google-analytics.com 'nonce-c5f5baeb-24ec-4a52-ae82-437707689e9a'; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; connect-src 'self' www.google-analytics.com`

**Comment by ianb** [comment]
I fixed this in 0b6cba0914f4bf346c445adf0d32641ab831627d – it was a regression due to specifying `connect-src` explicitly (which I added for GA beacon pings)
